features = [
    "hot"
]

code_watch_folders = ["./adapters/bevy_dexterous_developer/examples"]

asset_folders = ["./assets"]

[examples.simple_cli]
manifest_path = "./adapters/bevy_dexterous_developer/Cargo.toml"

[targets.x86_64-pc-windows-msvc]
builder = "Incremental"

[targets.x86_64-unknown-linux-gnu]
builder = "Incremental"

[targets.aarch64-apple-darwin]
builder = "Incremental"